### ISSUE TITLE
Use DateTime now for alarms

### ISSUE THREAD

**Issue by awickert** [NorthernWidget/ALog#19]
The chance for rollover during time-reading must not be as big a potential problem as I thought, because Chad changed our alarm-setting a while ago and we haven't noticed any problems. But it might cause some real issues.

This will require that we no longer set day of week; however, having a 24 hour interval means we can still have once-per-day data collection, and I cannot see why we would want less frequent than that.

**Comment by superchap123** [comment]
Andy implemented already
