### ISSUE TITLE
IDE library integration

### ISSUE THREAD

**Issue by awickert** [NorthernWidget/ALog#39]
Itlooks like the ALog library has disappeared from the Arduino IDE! The SFE_BMP180 one isn't there anyway. Need to add them!

When complete, remove this line from README.md:

```
***Currently not recommended, at least until all components can be downloaded this way***
```

**Comment by per1234** [comment]
I'm assuming this is referring to Library Manager. At the time this issue report was filed ALog was in fact not available for installation via Library Manager (https://github.com/arduino/Arduino/issues/6220). That has since been resolved and it is now in the Library Manager index.

**Comment by awickert** [comment]
Thanks -- you are correct!
